# Generated by Django 4.2.7 on 2024-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnfisaQuery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='anfisadatabase',
            options={'verbose_name': 'Имя', 'verbose_name_plural': 'Имена'},
        ),
    ]
