# Generated by Django 4.2.7 on 2024-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnfisaQuery', '0004_remove_timezones_city_timezones_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezones',
            name='city',
        ),
        migrations.AddField(
            model_name='timezones',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Город'),
        ),
    ]
