# Generated by Django 4.2.7 on 2024-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnfisaQuery', '0005_remove_timezones_city_timezones_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydatabase',
            name='answer',
            field=models.CharField(max_length=2000000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='querydatabase',
            name='query',
            field=models.CharField(max_length=2000000, verbose_name='Запрос'),
        ),
    ]
