# Generated by Django 4.2.7 on 2024-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnfisaQuery', '0008_alter_querydatabase_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='querydatabase',
            name='query',
            field=models.TextField(max_length=200, verbose_name='Запрос'),
        ),
    ]
